# Read permissions for dev in team-vision ns
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev-vision-binding
  namespace: team-vision
subjects:
- kind: Group
  name: dev
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io

---
# Read permissions for dev in team-api ns
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev-api-binding
  namespace: team-api
subjects:
- kind: Group
  name: dev
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io

---
# Create permissions for api group in team-api ns
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apibinding
  namespace: team-api
subjects:
- kind: Group
  name: api
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: createWithoutDelete
  apiGroup: rbac.authorization.k8s.io

---
# Create permissions for vision group in team-vision ns
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: visionbinding
  namespace: team-vision
subjects:
- kind: Group
  name: vision
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: createDeleteAllWithoutSecrets
  apiGroup: rbac.authorization.k8s.io

---
# Create permissions for tech-leads group in team-api ns
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: techleads-api-binding
  namespace: team-api
subjects:
- kind: Group
  name: tech-lead
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: createDeleteAllWithoutSecrets
  apiGroup: rbac.authorization.k8s.io

---
# Create permissions for tech-leads group in team-vision ns
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: techleads-vision-binding
  namespace: team-vision
subjects:
- kind: Group
  name: tech-lead
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: createDeleteAllWithoutSecrets
  apiGroup: rbac.authorization.k8s.io

---
# Create permissions clusterwide for SRE group
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secretsAdminBinding
subjects:
- kind: Group
  name: sre
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: secretsAdmin
  apiGroup: rbac.authorization.k8s.io
